### ISSUE TITLE
Fatal error when plugin removed and object-cache.php in-use

### ISSUE THREAD

**Issue by joonasvanhatapio** [tillkruss/redis-cache#101]
Hello,

I found a bug which causes the site crash after upgrading to the latest PHP 7.2 version.
When object-cache.php is left on the site, but the plugin uninstalled, the site gets a fatal 500 error causing site crash.

Ubuntu 18.04.2 LTS
- PHP-FPM: 7.2.18-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May  3 2019 09:24:01) ( NTS )
- php-redis/bionic,now 4.2.0-1+ubuntu18.04.1+deb.sury.org+1 amd64
- object-cache.php version: 1.4.2

PHP error log:
```
2019/05/07 12:01:42 [error] 1341#1341: *99813 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/wordpress/wp-content/plugins/redis-cache/includes/predis/autoload.php): failed to open stream: No such file or directory in /wordpress/wp-content/object-cache.php on line 463
PHP message: PHP Fatal error:  require_once(): Failed opening required '/wordpress/wp-content/plugins/redis-cache/includes/predis/autoload.php' (include_path='.:/usr/share/php') in /wordpress/wp-content/object-cache.php on line 463" while reading response header from upstream
```

Thanks!

**Comment by tillkruss** [comment]
Failing hard is probably a good thing in that case. In 1.4.3 there will be a better error message: https://github.com/tillkruss/redis-cache/commit/2df06b506e16236db912689572ab8963cfce72c8

If `WP_REDIS_GRACEFUL` is set, it won't fail hard anymore.
