### ISSUE TITLE
Error when negative expiry passed

### ISSUE THREAD

**Issue by Jon007** [tillkruss/redis-cache#104]
as discussed here, 
https://wordpress.org/support/topic/error-when-trying-to-get-a-get-a-cache-not-available/
negative cache expiries result in:
ERR invalid expire time in setex in wp-content/plugins/redis-cache/includes/predis/src/Client.php:370

there could be and sometimes are circumstances where a negative expiry period is passed but WordPress cache.php api would not raise any error about a negative expiry, in fact the set() has:
* @param int $expire Not Used.
so any such issue would be ignored until exposed by enabling this plugin.

So, while it seems correct to draw attention to the negative cache, it might be more correct that this redis plugin should be interface compatible with the default implementation by ignoring any negative expiry.

I would expect a negative expiry to cause a cache invalidation or deletion of previously cached object.

The related issue in woocommerce environment and pull request https://github.com/woocommerce/woocommerce/pull/23863
are not particularly relevant to this discussion because there could be other circumstances in which cache is requested with a negative expiry value.

**Comment by tillkruss** [comment]
Do you have any suggestions, other than fixing this at WC's end?

I think an exception on Redis' end is quite good. I don't like silently overwriting issues.

**Comment by Jon007** [comment]
well yes,
if this was a completely independent plugin then an exception is ok.
but as this plugin implements an interface which does not have an exception on these values then it should not: as I wrote I would expect a negative expiry to cause a cache invalidation or deletion of previously cached object.

**Comment by tillkruss** [comment]
So when `wp_cache_add()` is called with a negative expiry timestamp, it should forward the call to `wp_cache_delete()`?

**Comment by Jon007** [comment]
Well, it sounds logical yes.

**Comment by tillkruss** [comment]
Cool. I'll keep this open to see if any other plugin has an issue with this, except that one line in WC.
