### ISSUE TITLE
Error: Object cache drop-in could not be updated

### ISSUE THREAD

**Issue by xpat** [tillkruss/redis-cache#106]
The command _wp redis update-dropin_ doesn't update the Redis object cache drop-in but results in an error: Object cache drop-in could not be updated, preceeded by this: 

Warning: copy(/var/www/example.com/wp/wp-content/object-cache.php):failed to open stream:  Permission denied in /var/www/example.com/wp/wp-admin/includes/class-wp-filesystem-direct.php, the permissions for which are: -rwxr-xr-x 1 www-data class-wp-filesystem-direct.php

Any pointers?

Diagnostics: 
Status: Connected
Client: Predis (v1.1.1)
Drop-in: Valid
Ping: PONG
Redis Extension: Not Found
Predis Client: 1.1.1
PHP Version: 7.2.19-0ubuntu0.18.04.1
Multisite: No
Global Prefix: "wp_"
Blog Prefix: "wp_"
Global Groups: {
    "0": "blog-details",
    "1": "blog-id-cache",
    "2": "blog-lookup",
    "3": "global-posts",
    "4": "networks",
    "5": "rss",
    "6": "sites",
    "7": "site-details",
    "8": "site-lookup",
    "9": "site-options",
    "10": "site-transient",
    "11": "users",
    "12": "useremail",
    "13": "userlogins",
    "14": "usermeta",
    "15": "user_meta",
    "16": "userslugs",
    "33": "blog_meta"
}
Ignored Groups: [
    "counts",
    "plugins",
    "themes"
]
Dropins: 
 - Redis Object Cache Drop-In v1.4.3 by Till Krüss
Plugins: 
 - Akismet Anti-Spam v4.1.2 by Automattic (Inactive)
 - Food Online for WooCommerce v2.4.1 by Arosoft.se (Active)
 - Hello Dolly v1.7.2 by Matt Mullenweg (Inactive)
 - Redis Object Cache v1.4.3 by Till Krüss (Active)
 - Shipping Zones by Drawing for WooCommerce v1.0.5 by Arosoft.se (Active)

**Comment by tillkruss** [comment]
PHP/WP doesn't have permissions to write to your filesystem. You need to grant that.
