### ISSUE TITLE
Need a way to specify timeout and retry_interval

### ISSUE THREAD

**Issue by ffxluca** [tillkruss/redis-cache#107]
I am using redis-cache in a quite big production installation, paired with the pecl client (phpredis).

The latter allows specifying a few parameters like `timeout` and `retry_interval` (ref https://github.com/phpredis/phpredis#connect-open), and I'd very much like to do so, as the defaults are **0** which means **hang forever**.

I am not sure whether other non-pecl clients would allow these parameters, but again it would be really useful to have them in place.

I can help with pull-requests & friends

**Comment by tillkruss** [comment]
Yeah, Predis supports it as well. Feel free to submit a PR.
