### ISSUE TITLE
WP-CLI commands fail when using redis-cache as mu-plugin

### ISSUE THREAD

**Issue by maciej-laskowski** [tillkruss/redis-cache#113]
Hi!

When I try to run `php wp-cli.phar redis enable` or `php wp-cli.phar redis update-dropin` while using redis-cache as a mu-plugin I get an error:

`Whoops\Exception\ErrorException: copy(/var/www/domain.com/web/app/plugins/redis-cache/includes/object-cache.php): failed to open stream: No such file or directory in file /var/www/domain.com/web/wp/wp-admin/includes/class-wp-filesystem-direct.php on line 281`

Indeed `/var/www/domain.com/web/app/plugins/redis-cache/includes/object-cache.php` does not exist, the correct path would be `/var/www/domain.com/web/app/mu-plugins/redis-cache/includes/object-cache.php`

Enabling/disabling redis-cache via wp-admin works without problems.

**Comment by tillkruss** [comment]
You can use this plugin as a my-plugin. If you want support for that, please submit a PR.

**Comment by georgerushby** [comment]
Hi @tillkruss - your comment is a bit misleading. I am assuming that this plugin cannot be used as a mu-plugin?

**Comment by tillkruss** [comment]
@georgerushby: That sounded drunk. I fixed it up.

At this point, only the [business edition](https://wprediscache.com) supports being a MU-Plugin.

**Comment by feryardiant** [comment]
I was about to create a PR for this, but noticed that https://github.com/rhubarbgroup/redis-cache/commit/64072857700dac9e9016566e40a96e6dcf9e29dc commit already fix this issue

https://github.com/rhubarbgroup/redis-cache/blob/64072857700dac9e9016566e40a96e6dcf9e29dc/includes/cli/class-commands.php#L77-L81

So, my question when it would be available as stable version? or is it actually your _business edition_  version? @tillkruss

**Comment by tillkruss** [comment]
@feryardiant: Same as before. Currently only the Pro version supports a MU-plugin setup. 

The commit you mentioned is just a cleanup for v2.0. Pull requests for MU-plugin support are welcome.

**Comment by naxvog** [comment]
The current develop version will need some time to get into a stable state and is planned to be a version 2.0. If you feel adventurous you can use it but there might be undiscovered issues :wink:

@tillkruss Paths are more dynamic in the current develop branch - so the plugin does not need to be in the plugin directory any more. In a way this change might make future versions MU-plugin compatible. Further testing is obviously needed.

**Comment by feryardiant** [comment]
@tillkruss at this point I just want to run `php wp-cli.phar redis update-dropin` without any issue and don't know if there's any differentiation or advantage for any plugins of being `mu-pulgins` except it located on different directory and it `must-used`, obviously. And as far as I can tell your develop branch run well even it installed as `mu-plugins`

Thank you @naxvog, I'll go with develop branch then 😅

**Comment by tillkruss** [comment]
@feryardiant: Cool, looking forward to a PR if needed 🙌🏻
