### ISSUE TITLE
Caching "counts" cache group

### ISSUE THREAD

**Issue by maciej-laskowski** [tillkruss/redis-cache#114]
Hi, 

I am trying to remove `counts` from ignored cached groups. I did add
`define( 'WP_REDIS_IGNORED_GROUPS', ['plugins'] );` and checked if the constant is being loaded properly and it works. However it turns out that Wordpress runs `wp_cache_add_non_persistent_groups( array( 'counts', 'plugins' ) );` in wp-includes/load.php on line 586 (https://core.trac.wordpress.org/browser/branches/5.2/src/wp-includes/load.php#L586) which adds `counts` to ignored groups back regardless of the `WP_REDIS_IGNORED_GROUPS` setting.

What should I do to enable `counts` caching? Also, do you have any idea why counts caching is disabled by default? I did study the `wp_count_posts()` function (https://core.trac.wordpress.org/browser/branches/5.2/src/wp-includes/post.php#L2527) that sets this cache key and it seems to handle all the invalidation etc. so it seems really wasteful to recount posts on every request by default. This was already discussed in #74 but no solution was provided there.

**Comment by tillkruss** [comment]
I don’t know why it’s disabled by default. 

I also actually ever disabled the counts group. Let me know what you find out when digging into this.

**Comment by maciej-laskowski** [comment]
The problem is I cannot find a way of enabling `counts` caching other than commenting out line https://core.trac.wordpress.org/browser/branches/5.2/src/wp-includes/load.php#L586 in WP core which is not a solution. I hoped you might know another way but it seems I should try asking WP core devs about this. Thanks anyway, I will report back if I ever find a solution :)
