### ISSUE TITLE
REDIS with ACLs

### ISSUE THREAD

**Issue by CyberCr33p** [tillkruss/redis-cache#115]
Hello. I am new to REDIS. I want to see if it's possible to use REDIS with ACLs ( https://redis.io/topics/acl ) for multiple wordpress installations in same REDIS instance. Is it possible with ACLs each wordpress to have access to add/remove only it's own keys and don't have access to other users keys?

**Comment by tillkruss** [comment]
You can set a different Redis user for each installation, yup.
