### ISSUE TITLE
question about grobal_groups

### ISSUE THREAD

**Issue by niciyan** [tillkruss/redis-cache#116]
Hi

I have found your great plugin and read source files.
I got a question that I want to understand.
(I have no experience with wordpress plugin development.)

In object-cache.php, WP_Object_Cache class has $global_groups field.
It has 17 group names by default.

What is $global_groups used for?
Why you defined the default group names?

**Comment by tillkruss** [comment]
That's multisite stuff.

**Comment by niciyan** [comment]
Thank you for replying.
I will check it out more.
