### ISSUE TITLE
Bug ?? in WP_Object_Cache::build_key()

### ISSUE THREAD

**Issue by robita34** [tillkruss/redis-cache#119]
https://github.com/tillkruss/redis-cache/commit/13216e313f9f1e56f2b4153b2888fc024f5f0e54#diff-3ea3a8942f84c506446c32d498ac655dR1187

Should the above code be the following code?

```php
$key = str_replace(':', '-', $key);
```

**Comment by tillkruss** [comment]
Thanks!
