### ISSUE TITLE
mb_strtolower dependency check

### ISSUE THREAD

**Issue by chrislarrycarl** [tillkruss/redis-cache#120]
Version 1.5 introduces use of [`mb_strtolower()` in the `build_key()` method of the drop-in ](https://github.com/tillkruss/redis-cache/blob/master/includes/object-cache.php#L1200). Some environments won't have the optional multibyte string package installed resulting in a function undefined error. It'd be ideal if there was a check for this function and a fallback or warning to users if they are on a suboptimal server setup.

Thanks for a great plugin!

**Comment by tillkruss** [comment]
Thanks! I’ll fix that in the next version.
