### ISSUE TITLE
Please consider donating 💖

### ISSUE THREAD

**Issue by tillkruss** [tillkruss/redis-cache#121]
Developing, improving and maintaining open-source plugins takes a lot of time. Please consider sponsoring the development of this plugin, or one-off donations.

https://github.com/sponsors/tillkruss

**Comment by tillkruss** [comment]
Nobody is doing it, meh.

**Comment by lkraav** [comment]
Premium plugin, couple of different price tiers, easily billable to company expense budget, is probably the only useful way. This is from the customer side, I don't have a premium plugin product on the market myself.. yet.
