### ISSUE TITLE
Plesk issue with socket connection

### ISSUE THREAD

**Issue by naxvog** [tillkruss/redis-cache#123]
Using the default Plesk phpredis version (3.0.0) a socket connection will fail.
It seems as the additional parameters on the connection method introduced will cause this issue.
Connecting via `$this->redis->connect($parameters['host']);` will still work.

I would suggest adding a version check to the pecl connection process to avoid this issue as many Plesk users won't bother updating their phpredis.

As a workaround I installed the current phpredis version (using Ubuntu 16 LTS):
```sudo apt install plesk-73-dev```
```sudo /opt/plesk/php/7.3/bin/pecl install redis```
Make sure to reinitialize the module using the global PHP setting and disabling/enabling the redis extension.

**Comment by tillkruss** [comment]
Thanks! Can you submit a PR?

**Comment by naxvog** [comment]
Investigated further:
seems as phpredis introduced the parameter in [version 3.1.3](https://github.com/phpredis/phpredis/commit/b56dc49eec94bbb9b0e26aa3d16582c3590029d6) so we have to check for this particular version.

Will try to submit a PR in the coming days.
