### ISSUE TITLE
Flush don't work with WP_REDIS_SELECTIVE_FLUSH set to TRUE

### ISSUE THREAD

**Issue by kionez** [tillkruss/redis-cache#126]
With WP_REDIS_SELECTIVE_FLUSH set to TRUE, flushing cache don't work as expected.
I have to use WP_REDIS_SELECTIVE_FLUSH because I have many different wordpress installation uplodaed by users and I must definitely keep them "separate".

After some digging in the code and a bit of redis-cli (expecially MONITOR command), i see that the LUA script was not executed, if I try to copy-paste and run manually it gives me an error:

```
127.0.0.1:6379> "EVAL" " local cur = 0\n local i = 0\n local tmp\n repeat\n tmp = redis.call('SCAN', cur, 'MATCH', 'MYDOMAIN.com*')\n cur = tonumber(tmp[1])\n  if tmp[2] then\n for _, v in pairs(tmp[2]) do\n redis.call('del', v)\n i = i + 1\n  end\n end\n until 0 == cur\n return i" "0"

(error) ERR Error running script (call to f_523831630e0cc0dbf20c9141913c81f1bec591ba): @user_script:9: @user_script: 9: Write commands not allowed after non deterministic commands. Call redis.replicate_commands() at the start of your script in order to switch to single commands replication mode.
```

So, i edit my wp-content/object-cache.php adding `redis.replicate_commands()` at the start of LUA script (lines  820 and 860) and now cache is correctly flushed (via dashboard button or via `wp cache flush` command)

I don't know if this is the correct solution, I don't have much knowledge of redis, I try to read https://redis.io/commands/eval but I can't figure out.

Hope it helps!

Here some info:
Wordpress: 5.3 and 5.2
Redis Object Cache: 1.5.0
Client: PhpRedis (v4.3.0)
Redis Extension: 4.3.0
Predis Client: 1.1.1
PHP Version: 5.6.40-0+deb8u6
Redis Object Cache Drop-In v1.5.0 by Till Krüss
Redis Server: 3.2.8

**Comment by tillkruss** [comment]
Thanks for the report! Can you submit a PR with the fix?

**Comment by kionez** [comment]
I've search for more info about `redis.replicate_commands()` and it seems a correct way to fix this kind of situation. Hope it helps :)
