### ISSUE TITLE
redis-cache plugin produces loop in WP 5.3

### ISSUE THREAD

**Issue by regenpfeifer** [tillkruss/redis-cache#129]
Hello,

I am using redis-cache plugin with WP 5.3 and it worked fine until recently. Now it produces an infinite loop when I am trying to open the dashboard with 'mysite.tld/wp-admin'. I am getting the message "your database is already up to date" (in german) and a button "continue" which leads me back to the same page; so I cannot longer access the dashboard. I have to delete the file 'object-cache.php' in my wp-content directory, which deactivates the redis-plugin, but the error comes back, when this file will be recreated.

My configuration:

-- WP 5.3 hosted on Ubuntu 16.04 LTS --
Status (Redis Plugin): Deaktiviert
Redis Version: Unknown
Client: 
Drop-in: Invalid
Redis Extension: 5.0.2
Predis Client: 1.1.1
PHP Version: 7.3.11-1+ubuntu16.04.1+deb.sury.org+1
Multisite: No
Dropins: 
 - advanced-cache.php v by 
Plugins: 
 - Academic Blogger's Toolkit v5.2.2 by Derek P Sifford (Active)
 - Akismet Anti-Spam v4.1.3 by Automattic (Active)
 - AMP v1.4.1 by AMP Project Contributors (Active)
 - Broken Link Checker v1.11.9 by ManageWP (Active)
 - Clean Image Filenames v1.2.1 by Upperdog (Active)
 - CMB2 v2.6.0 by CMB2 team (Active)
 - Co-Authors Plus v3.4 by Mohammad Jangda, Daniel Bachhuber, Automattic (Active)
 - Code Snippets v2.13.3 by Shea Bunge (Active)
 - Florian Theme Addons v1.3 by MagniumThemes (Active)
 - Imagify v1.9.8.1 by WP Media (Active)
 - Jetpack by WordPress.com v7.9 by Automattic (Active)
 - Kirki Customizer Framework v3.0.44 by Ari Stathopoulos (@aristath) (Active)
 - Loco Translate v2.3.1 by Tim Whitlock (Inactive)
 - MC4WP: Mailchimp for WordPress v4.7 by ibericode (Inactive)
 - Members v2.2.0 by Justin Tadlock (Active)
 - Open Graph and Twitter Card Tags v2.2.7.2 by Webdados (Active)
 - Press This v1.1.1 by WordPress Contributors (Active)
 - Redis Object Cache v1.5.2 by Till Krüss (Active)
 - Regenerate Thumbnails v3.1.2 by Alex Mills (Viper007Bond) (Inactive)
 - Responsive Lightbox & Gallery v2.2.1 by dFactory (Inactive)
 - Smash Balloon Instagram Feed v2.1.2 by Smash Balloon (Active)
 - VaultPress v2.0.1 by Automattic (Active)
 - WP-PageNavi v2.93.1 by Lester 'GaMerZ' Chan (Active)
 - wp-Typography v5.6.0 by Peter Putzer (Active)
 - WP Rocket v3.4.1.2 by WP Media (Active)
 - YOURLS Link Creator v2.1.1 by Andrew Norcross (Active)

On my server I can access redis with 'redis-cli' ant the redis cache seems to work fine with my nextcloud setup. I have tried to deactivate wp-rocket cache, which didn't help, unfortunately.

What could I do to solve this problem=

Yours, regenpfeifer

**Comment by tillkruss** [comment]
Try a Redis flush, if that doesn't fix it, it's not this plugin 👍🏻

**Comment by regenpfeifer** [comment]
Thank you, that solved the problem!
