### ISSUE TITLE
collecting metrics without consent

### ISSUE THREAD

**Issue by sawanoboly** [tillkruss/redis-cache#131]
Hi,

https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#7-plugins-may-not-track-users-without-their-consent

**Comment by tillkruss** [comment]
Does that apply to system metrics? Nothing personal is transmitted. It says “user data”.

**Comment by sawanoboly** [comment]
Well, I can’t say about interpretation of guidelines. 🤷🏻‍♂️

IMO, sending metrics should be at least opt-in, and I think host names and some other configuration information are personal information.

**Comment by tillkruss** [comment]
Mhh, I was using the URL as unique identifier, but I could change that probably. 

What “other” configuration options do you consider personal that are being sent?

I’ll document the constants, I added it to the change log since that’s why most people read.

**Comment by sawanoboly** [comment]
If you need an identifier, it's better to hash the URL so it can't be restored.

The other settings will be different for each individual, so my opinion is just reference as. For example, woocommerce and is_multisite seem to collect too much information.

I'm not involved in the culture of the WordPress community, so I'm not sure what the overall opinion is.
However, in any case, it is safer to collect metrics after user's consent.

**Comment by naxvog** [comment]
Strictly speaking the data is not necessary as the plugin does not rely on the information to function correctly so it should be opt-in.
Regardless of the opt-in there should also be a message/page explaining what data is collected.

Personally I would advise a client of mine to either do the opt-in plus the "what is collected" information page or to re-evaluate if the data is worth the hassle.

**Comment by tillkruss** [comment]
Making it opt-in would defeat the purpose, which is to have an insight into whether certain features could be removed or ported into extensions. 

There are 50.000+ active installations and the last few releases haven’t been smooth. 

For example if only a few people still use HHVM, it might as well be dropped to simplify the codebase. 

Selective flushing is quite troublesome as well. I’m thinking of moving it into an extension to provide a better experience. 

Another one is Predis, the library hasn’t been updated in two years and there are already PHP 7.3 issues popping up. I assume 7.4 and 7.5 will get much worse or even break Predis. 

I want to know how many installations rely on Predis, to decide if it NEEDS to be replaced by another pure PHP client or if we can switch to PhpRedis only.

I doubt anyone will opt-in to collect metrics or that those few will create a large enough sample. 

On another note: I’m personally big into privacy. I run VPNs, use 1.1.1.1 everywhere and even made a plugin to prevent bots from harvesting emails. 

Lastly, I’d argue the collected data is not personal or WPs vague “user data” term. No emails, no names, no behavioral info is collected, not even usage data.  

With all that in mind:

1) The plugin can stop collecting metrics and  I’ll make blind decisions about the plugin, probably affecting tens of thousands of installations. (Predis users)

2) Keep collecting metrics and provide a better experience and easier migrations in the future for everyone.

**Comment by sawanoboly** [comment]
If predis case,  why don't you warn the environment that uses php7.3 or higher and predis. Like you put a professional ad on the top of the admin screen.
I think it is the responsibility of the user.

**Comment by mt8** [comment]
Any data sent to the user without notice is not welcome. 
The default should be turned off.

**Comment by tillkruss** [comment]
WordPress is by default collecting exactly the same data, without the users consent or mentioning it anywhere. 

https://github.com/WordPress/WordPress/blob/e1996633228749cdc2d92bc04cc535d45367bfa4/wp-includes/update.php

**Comment by tillkruss** [comment]
@sawanoboly: Warn them about what?

**Comment by sawanoboly** [comment]
`predis will probably not be supported in the future because maintenance has stopped and there are compatibility issues.`

You can decide how long you want to support without collecting data. For example, changing the major version of a plugin.

**Comment by tillkruss** [comment]
I documented the constants 👍🏻

**Comment by tillkruss** [comment]
For reference this is what WordPress collects without consent or the ability to turn it off:

- URL
- User count
- Multisite (bool)
- WP locale
- Number of blogs (multisite)
- Active plugins
- Installed translations
- WP version
- PHP version
- MySQL version

**Comment by tillkruss** [comment]
@sawanoboly: It looks like WP 5.2 added some useful that I wasn't aware of: https://core.trac.wordpress.org/ticket/43992

I'll look into whether this only works for plugin installs or also for updates 👌🏻

**Comment by sawanoboly** [comment]
The description of WP_REDIS_DISABLE_METRICS should provide a list of what has been collected first. That will helps understanding clearly what you want to do.

**Comment by naxvog** [comment]
[Asked in the WordPress pluginreview slack channel.](https://wordpress.slack.com/archives/C1LBM36LC/p1574752575246900)
Pointed to this issue as well as to the specific line in the code collecting the data.

> Answer is no. It also says that plugins aren't allowed to call home.

**Comment by Otto42** [comment]
Well, I can be perfectly clear about this. Collecting the data in the way you are is a violation of the guidelines, and your plugin has been removed from the WordPress.org plugin directory until you fix the issue. Simple enough.

**Comment by sawanoboly** [comment]
I think the chosen method was exaggerated for your purpose. Do your best to update 👍

**Comment by tillkruss** [comment]
@Otto42: Got it. I pushed v1.5.4 that removed the metrics entirely.

**Comment by sawanoboly** [comment]
@tillkruss 

Could you please add a process to clear already registered cron events?

https://github.com/tillkruss/redis-cache/commit/535c6900f21e99d1854826f3a1fe46885d30644a

```
add_action( 'admin_init', function() {
	if ( wp_next_scheduled( 'redis_gather_metrics' ) ) {
		wp_clear_scheduled_hook('redis_gather_metrics');
	}
});
```

**Comment by tillkruss** [comment]
@sawanoboly: Please submit a PR.
