### ISSUE TITLE
Breaks when objects are modified in place after being cached

### ISSUE THREAD

**Issue by Gaelan** [tillkruss/redis-cache#140]
Automattic's Eventbrite API plugin does something slightly strange: it [stores an object as a transient](https://github.com/Automattic/eventbrite-api/blob/8b1d23426da4fae7e2754531ddad12a2ac20622b/inc/class-eventbrite-manager.php#L73), then [modifies the same object in place](https://github.com/Automattic/eventbrite-api/blob/8b1d23426da4fae7e2754531ddad12a2ac20622b/inc/class-eventbrite-manager.php#L179). When reading the cached value later, it expects to get the unmodified value. In default WordPress, this works fine—the code for both [options](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-includes/option.php#L313) and [the object cache](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-includes/cache.php#L676) `clone` objects before caching them in-memory, so the later modifications don't affect the cache. On the other hand, redis-cache caches objects in-memory as passed, without cloning; this causes the Eventbrite API plugin to break. It would be great if redis-cache's behavior was consistent with Wordpress's here.

**Comment by tillkruss** [comment]
Fixed by #141.
