### ISSUE TITLE
Recommended Redis version?

### ISSUE THREAD

**Issue by ethanclevenger91** [tillkruss/redis-cache#143]
This may be a dumb question if I were more familiar with the intricacies of Redis, but is there a recommended version of Redis that this plugin is compatible with? Or a version in particular it's tested with? Would love to see that documented. 

Currently running 4.0.10 and I assume updating to 5.x.x is fine but wanted to verify.

**Comment by tillkruss** [comment]
This plugin doesn’t really use any special features, so Redis 3 or newer is great. I’m always running the latest version of Redis just for the performance gains.
