### ISSUE TITLE
Add PHPRedis (pecl) TLS Support

### ISSUE THREAD

**Issue by timofeycom** [tillkruss/redis-cache#146]
Hi Till, per our conversation on [WP Support](https://wordpress.org/support/topic/bug-phpredis-pecl-does-not-work-with-tls-scheme/) please add TLS support for PHPRedis (pecl). I've created a patch for this.

# Patch
Rename to patch.diff
[patch.diff.txt](https://github.com/tillkruss/redis-cache/files/4151094/patch.diff.txt)

# Description of the Issue
Redis-Cache 1.5.6 fails to check for `WP_REDIS_SCHEME` when connecting via PHPRedis.

PHPRedis allows TLS connection in the form of tls://127.0.0.1, see https://github.com/phpredis/phpredis#example-1

# Solution / Description of the Patch
This patch add a line of code that checks for `WP_REDIS_SCHEME` when connecting via PHPRedis.

I am currently using this patch to successfully connect to DigitalOcean Redis managed database via TLS.

Let me know if you need anything to get this implemented.

Thank you!
Tim

**Comment by tillkruss** [comment]
@timofeycom: Can you submit a PR here on GitHub, instead of the patch file?

**Comment by timofeycom** [comment]
@tillkruss I'm getting a permissions error 403 when I try to submit Pull Request to the master. It only allows me to submit it to the page-cache branch. Am I missing something?

Thanks

**Comment by tillkruss** [comment]
I see your fork, you'd need to commit to a branch on https://github.com/timofeycom/redis-cache.
