### ISSUE TITLE
RedisCluster AUTH

### ISSUE THREAD

**Issue by peder-lundqvist** [tillkruss/redis-cache#148]
Redis cluster with password authorization is not working at all in the current version. 
On line 469 in object-cache.php $this->redis = new RedisCluster(null, array_values(WP_REDIS_CLUSTER));
it shoult instead connect with an array of passwords and timeouts
$this->redis = new RedisCluster( NULL, array_values(WP_REDIS_CLUSTER), 5, 5, true, WP_REDIS_PASSWORD);
Later on line 504 the rediscluster object does not contain ->auth

**Comment by tillkruss** [comment]
Thanks @peder-lundqvist. Can you submit a PR with the fix?

**Comment by peder-lundqvist** [comment]
I have no code that is working, just did a quick test to se if it could work.

**Comment by tillkruss** [comment]
Ah, I see this line needs to be extended: https://github.com/tillkruss/redis-cache/blob/master/includes/object-cache.php#L469

**Comment by tillkruss** [comment]
I'll release a fix this week.

**Comment by tillkruss** [comment]
Hey @peder-lundqvist, can you please try connecting to your cluster using `master`? I resolved the issue in 40bdf63a1c74b71c0eaa22da651d6c6f3dfaf1d6.

**Comment by tillkruss** [comment]
Download: https://github.com/tillkruss/redis-cache/archive/master.zip

**Comment by tillkruss** [comment]
Fixed in 1.5.7
