### ISSUE TITLE
Wordpress time stamp issues

### ISSUE THREAD

**Issue by smx06** [tillkruss/redis-cache#149]
Hi
Had a strange problem in Wordpress 5.3.1 + Redis object cache 1.5.6 plugin
Just installed 
apt-get install redis-server
apt-get install php-redis
systemctl start redis.service
systemctl enable /lib/systemd/system/redis-server.service

then installed the plugin and activated + enabled cache in WP Redis Obj cache plugin settings
all worked well and much faster than before
untill i found a big problem (next day) 
when i updated time attributes of scheduled post (created before redis installation) it just didn't work - post looked liked published but edited timestamp didn't change! (many attempts to change the post time failed)
then i logged out and tried to login again - login failed 
So seems the db queries were not working correct

So the question is what i did wrong when installing? maybe i did miss some wp-config settings?  
Sorry for dumb questions, does redis use some files while working? (cause file permissions are restrictive for wordpress folder preventing files creation)

thank you for support!

Thank you for support

**Comment by tillkruss** [comment]
Are you using any plugins that handle the scheduled posts?

**Comment by smx06** [comment]
No, i don't afair. Also scheduling is the minor problem comparing to login problem
(no logged in status after successfull login)
Do you think disabling all plugins could help?

**Comment by tillkruss** [comment]
I’d try a cache flush and see if the error persists.
