### ISSUE TITLE
Document REDIS_SERVERS Reader/Writer configuration

### ISSUE THREAD

**Issue by natesymer** [tillkruss/redis-cache#150]
I saw in the docs that you can configure Redis Object Cache to use multiple redis servers (presumably a master and replicas). This is great, but how can I specify which one is read/write (the primary) and readonly (the replicas)?

**Comment by tillkruss** [comment]
If you're using Predis, you can use the alias:

```php
define( 'WP_REDIS_SERVERS', [
    'tcp://127.0.0.1:6379?database=5&alias=master',
    'tcp://127.0.0.2:6379?database=5&alias=slave-01',
] );
```
