### ISSUE TITLE
Exception: php_network_getaddresses: getaddrinfo failed: Name or service not known 

### ISSUE THREAD

**Issue by tzachristas** [tillkruss/redis-cache#152]
I can access redis host using: redli --tls -h private-db-redis-do-user-623918-0.a.db.ondigitalocean.com -a *********** -p 25061

> PING
> PONG

Plugin Diagnostics throw exception! Any suggestions?

Status: Not Connected
Client: PhpRedis (v4.3.0)
Drop-in: Valid
Connection Exception: php_network_getaddresses: getaddrinfo failed: Name or service not known (RedisException)
Redis Extension: 4.3.0
Predis Client: 1.1.1
PHP Version: 7.3.13
Redis Version: Unknown
Multisite: No
Global Prefix: "hia_"
Blog Prefix: "hia_"
WP_REDIS_SCHEME: "tls"
WP_REDIS_HOST: "private-db-redis-do-user-623918-0.a.db.ondigitalocean.com"
WP_REDIS_PORT: "25061"
WP_REDIS_PASSWORD: "****************"
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs"
]
Ignored Groups: [
    "counts",
    "plugins",
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "blog_meta",
    "bad-actor",
    "themes"
]
Unflushable Groups: []

**Comment by tillkruss** [comment]
Looks like the Redis instance is up, but your PHP process can't access the Redis host. Looks like a policy/permissions issue on your Redis instance.

**Comment by tzachristas** [comment]
Thank you for your reply. 

You are right i had to use php-pecl-redis5 (and remove the previous php-pecl-redis4-4.3.0)
