### ISSUE TITLE
Can't exclude object

### ISSUE THREAD

**Issue by rashkoff** [tillkruss/redis-cache#153]
Hello
I can't isolate objects 
this is the situation:
Already restart the server, clean the cache, clean the browser cache, trying from different browsers...

**this the config into top wp-config**

define(‘WP_REDIS_IGNORED_GROUPS’, [
‘counts’,
‘plugins’,
‘wishlist-items’,
‘wishlists’,
‘convert_url’,
]);

**this is the result form debug bar plugin:**

wp:wishlists:wishlist-default-1 – 0.01k
wp:wishlists:wishlist-id-1 – 0.29k
wp:wishlists:wishlist-token- – 0.29k
wp:wishlist-items:item-222621 – 0.29k
wp:wishlist-items:item-137880 – 0.29k
wp:wishlist-items:item-237165 – 0.29k
wp:wishlist-items:item-214941 – 0.29k
wp:wishlist-items:item-216822 – 0.29k
wp:wishlist-items:item-222609 – 0.29k
wp:wishlist-items:item-8 – 0.27k

**this is the diagnostic form Redis plugin:**

Status: Connected
Client: PhpRedis (v5.2.1)
Drop-in: Valid
Ping: 1
Redis Extension: 5.2.1
Predis Client: 1.1.1
PHP Version: 7.3.17
Redis Version: 3.2.12
Multisite: No
Global Prefix: “wp_”
Blog Prefix: “wp_”
WP_REDIS_IGNORED_GROUPS: [“counts”,”plugins”,”wishlist-items”,”wishlists”,”convert_url”]
Global Groups: {
“0”: “blog-details”,
“1”: “blog-id-cache”,
“2”: “blog-lookup”,
“3”: “global-posts”,
“4”: “networks”,
“5”: “rss”,
“6”: “sites”,
“7”: “site-details”,
“8”: “site-lookup”,
“9”: “site-options”,
“10”: “site-transient”,
“11”: “users”,
“12”: “useremail”,
“13”: “userlogins”,
“14”: “usermeta”,
“15”: “user_meta”,
“16”: “userslugs”,
“33”: “blog_meta”
}
Ignored Groups: [
“counts”,
“plugins”,
“wishlist-items”,
“wishlists”,
“convert_url”,
“themes”,
“wordfence”,
“wordfence-ls”,
“WPML_ST_Package_Factory”,
“atum-stock-manager-for-woocommerce”
]

What I’m doing wrong?

Thanks

**Comment by tillkruss** [comment]
After flushing the cache, are the groups still being cached?

**Comment by rashkoff** [comment]
Yes, flushing the cache, deactivate the plugin, restart apache, restart php-7.3... deactivate all plugins like wp-rocket ... nothing helps.

**Comment by tillkruss** [comment]
Looks like the ignored groups are still cached for the request, but not in Redis.

Try running this to see if Redis actually has keys or not.

```
redis-cli
KEYS wp:wishlist*
```

**Comment by rashkoff** [comment]
this is the result
`(empty list or set)`

**Comment by tillkruss** [comment]
That means nothing is cached in Redis.
