### ISSUE TITLE
Set HTTP Response Header to show cached response

### ISSUE THREAD

**Issue by ratzrattillo** [tillkruss/redis-cache#154]
Hello Till,

i really appreciate your work on this plugin and i already use it successfully on my development page.
However i have a suggestion: When uing the plugin, you can clearly see which reponse was served by redis, as the speed is by far higher. However, a HTTP-Header indicating a cached response would be great.
Do you have an idea how to implement this? Do you think this could be included in this plugin?
Suggestion:
X-Redis-Cache: HIT
X-Redis-Cache: MISS
X-Redis-Cache: BYPASS (If that is possible/necessary)

What do you think?

Best regards!

**Comment by tillkruss** [comment]
Mhh, we could add something like this:

```
X-Redis-Cache: hits=200, misses=10
```

**Comment by ratzrattillo** [comment]
Yes, showing the hits and misses would be even better.
A header is really nice, as it shows you the hits and misses on a per request base.
A cumulated result in an HTML comment would be a nice addition to show the complete performance of a page load.
Sounds good imo!

**Comment by tillkruss** [comment]
@ratzrattillo: Do you want to open a pull request? Check out the `stats()` method in the object cache, it's showing how to fetch the data.

**Comment by naxvog** [comment]
Should be an opt-in option as this would only be an information leak otherwise.

**Comment by ratzrattillo** [comment]
@tillkruss 
I am not an experienced wordpress developer, but i can make the following suggestions:
I would introduce new variables like these in the WP_Objects_Cache class:

`public $hits_per_request = 0;
public $misses_per_request = 0;
public $new_cached_per_request = 0;`

@naxvog I would check in that class, if a debug variable is set in wp-config:
`if (defined('WP_REDIS_CACHE_HEADER') && WP_REDIS_CACHE_HEADER) {
			error_log("WP_REDIS_CACHE_HEADER set to true");
			if(false === has_action('send_headers', 'wp_cache_set_cache_stats_header')) {
				error_log("adding action send_headers wp_cache_set_cache_stats_header");
				add_action('send_headers', 'wp_cache_set_cache_stats_header', 10, 1);
			}
		}
		else{
			error_log("WP_REDIS_CACHE_HEADER set to false or undefined");
			if(false !== has_action('send_headers', 'wp_cache_set_cache_stats_header')) {
				error_log("removing action send_headers wp_cache_set_cache_stats_header");
				remove_action('send_headers', 'wp_cache_set_cache_stats_header', 10, 1);
			}
		}`

I would also add the following functions  in object-cache.php (Outside the WP_Object_Cache class) to build the HTTP-Header and get the required information in the header

`/**
 * Build HTTP response header to display basic cache stats
 *
 * @return string
 */
function wp_cache_set_cache_stats_header($headers) {
	
	global $wp_object_cache;
	
	#error_log(print_r($headers));
	header("X-Redis-Cache: Total-Hits=" . $wp_object_cache->cache_hits . ", Total-Misses=" . $wp_object_cache->cache_misses . "; Hits: " . $wp_object_cache->hits_per_request . ": Misses: " . $wp_object_cache->misses_per_request . "; New Cached: " . $wp_object_cache->new_cached_per_request);
	$wp_object_cache->hits_per_request = 0;
	$wp_object_cache->misses_per_request = 0;
	$wp_object_cache->new_cached_per_request = 0;
	#error_log($headers['X-Redis-Cache']);
	return $headers;
}

/**
 * Set the global variables for hits per request and misses per request
 *
 * @return string
 */
function filter_cache_get($value, $key, $group, $force, $found) {
			
	global $wp_object_cache;
	
	error_log("filter_cache_get...");
	error_log("Found:" . $found);
	
	if($found == 1){
		$wp_object_cache->hits_per_request++;
	}
	else{
		$wp_object_cache->misses_per_request++;
	}
}
add_filter( 'redis_object_cache_get_value', 'filter_cache_get', 10, 5 );

/**
 * Set the global variables for new cached per request
 *
 * @return string
 */
function action_cache_set($key, $value, $group, $expiration, $execute_time) {
			
	global $wp_object_cache;
	
	error_log("action_cache_set...");
	error_log("ExecutionTime:" . $execute_time);
	$wp_object_cache->new_cached_per_request++;
}
add_action( 'redis_object_cache_set', 'action_cache_set', 10, 5 );	`

This should give a debug header like this:
`X-Redis-Cache: Total-Hits=1314; Total-Misses=25; Hits: 28; Misses: 0; New Cached: 22`

However these values seem strange to me, as misses always are 0...

In order to not display this header, when serving responses from fastcgi cache (as they would not contain correct data), the following snippet might be added to e.g. nginx.conf:

`if ($upstream_cache_status = "HIT") {
	fastcgi_hide_header X-Redis-Cache;
}`

Let me know, if this is a good approach..

**Comment by ratzrattillo** [comment]
Sorry guys, that code formatting looks terrible :/

**Comment by tillkruss** [comment]
@ratzrattillo: You can just access the `$cache_hits` and `$cache_misses` variables.

**Comment by ratzrattillo** [comment]
As you can see, i do that. But it seems like the number of cached entries does not change when executing small or huge queries. Makes me wonder if the data saved in these variables is correct... Or not showing the "per request" data.

**Comment by tillkruss** [comment]
You can't use a HTTP header, because the body/content of WP might trigger a lot of cache lookups.

**Comment by tillkruss** [comment]
I branched a rudimentary version in #156. Let's move this discussion there.

**Comment by tillkruss** [comment]
### WP Super Cache by Automattic

```
<!-- Dynamic page generated in 0.103 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2020-05-29 17:39:46 -->
<!-- super cache -->
```

### WP Fastest Cache

```
<!-- WP Fastest Cache file was created in 0.014904975891113 seconds, on 29-05-20 17:41:42 --><!-- need to refresh to see cached version -->
```

### LiteSpeed Cache

```
<!-- Page supported by LiteSpeed Cache 3.2 on 2020-05-29 17:42:52 -->
```

### W3 Total Cache

```
<!--
Performance optimized by W3 Total Cache. Learn more: https://www.boldgrid.com/w3-total-cache/

Page Caching using disk: enhanced 

Served from: wordpress.test @ 2020-05-29 17:44:07 by W3 Total Cache
-->
```

### Batcache by Automattic

```
<!--
	generated $seconds_ago seconds ago
	generated in $generation seconds
	served from batcache in $serving seconds
	expires in $expires seconds
-->
```
