### ISSUE TITLE
"info() expects at least 1 parameter” Warning after fresh install

### ISSUE THREAD

**Issue by dealer-solutions-gene** [tillkruss/redis-cache#155]
I've just installed this plugin **Version: 1.5.7** using client **PhpRedis (v5.2.2)** with a AWS ElastiCache **Redis engine of 5.0.6**, and I receive this error after configuring the pluging as a Redis cluster

> Warning: RedisCluster::info() expects at least 1 parameter, 0 given in /var/www/app/web/app/object-cache.php on line 595

This error is printing in the wordpress admin console.

The code of the line this warning prints is `$info = $this->redis->info();`

I've configured it as a cluster using AWS Redis

```
define( 'WP_REDIS_CLUSTER',['tcp://blahblahblah.blahblahblah.clustercfg.apse2.cache.amazonaws.com:6379']);
define( 'WP_CACHE_KEY_SALT', 'development' );
```

**Comment by tillkruss** [comment]
@dealer-solutions-gene: I just pushed 01c18b8014b368e8511a610f056dacc669fa7e56. Could you try the `object-cache.php` from master to see if that resolves it for you?

https://raw.githubusercontent.com/tillkruss/redis-cache/master/includes/object-cache.php

**Comment by dealer-solutions-gene** [comment]
@tillkruss Yeah, that looks like it addresses the issue when clustering is used. tested it and the warning message is cleared now.

**Comment by tillkruss** [comment]
1.5.8 is going out shortly.
