### ISSUE TITLE
Please advise. Appears to be a typo in constructor causing flush exception. Plugin needed for site. Thanks

### ISSUE THREAD

**Issue by rereich27** [tillkruss/redis-cache#157]
object-cache.php:598 
$this->redis->info();

Should be this?
$info = $this->redis->info();

**Comment by tillkruss** [comment]
Yes, can you submit a PR? I can release a fix tomorrow.

**Comment by rereich27** [comment]
Ok thanks!

**Comment by tillkruss** [comment]
Closed via #158
