### ISSUE TITLE
1.5.9: Key Prefix: "cr_" displays "Consider using a shorter, human-readable prefix." notice

### ISSUE THREAD

**Issue by lkraav** [tillkruss/redis-cache#159]
I'm not sure this algoritm makes sense, at least as is. "cr" is about as short as it's going to get. It's not clear whether both conditions are important for a "good" prefix, or not.

Why not let people have whatever prefix they want and not cast extra doubt?

**Comment by tillkruss** [comment]
Yeah, the `ctype_alnum()` is too simple, I'll turn this into a regex.

**Comment by tillkruss** [comment]
Thoughts on https://github.com/tillkruss/redis-cache/commit/118be44ae852827994d54174638b1090adcb28a4?

**Comment by naxvog** [comment]
@tillkruss Not sure if this is the right topic but as you are working on the "detection" condition - please add a constant to disable the check.
I for one do use the plugin in an automated setting generating random prefixes for our customers. A message like this would just confuse them as they cannot change the prefix.

**Comment by lkraav** [comment]
Why do we need to concern ourselves with suggestions in the first place? What problem have you seen in the wild that it tries to solve? Maybe a simple prefix generator that expresses what we want users to get to, is a better tool?

**Comment by tillkruss** [comment]
I saw plenty of users use a "salt" due to the constant name, which tends to be 60+ characters and contains `$*&@#}{`, etc.

**Comment by tillkruss** [comment]
@naxvog: What do you auto generated prefixes look like?

**Comment by naxvog** [comment]
Plain key generation:
```php
$payload = implode( '::', [ $_SERVER['HOME'], time() ] );
$cache_key_salt = hash( 'sha512', $payload );
$cache_key_salt = self::base_encode( $cache_key_salt, 16 );
```
The base_encode method converts the base 16 sha512-key to a defined base 66 string (regex: `[a-zA-z0-9\-_.~]`)
Some examples of keys generated by this method:
* `1iQraww8_uJUvSGowgPtTr.FIIfX~Ye~6vEe`
* `rHbP6A2rP_4EVNCbF.HtM~36-jdguaeB-J8`
* `1s7x0ST-52qcwvYeKovA9wl~T2LKpneMAJEu`

The generated key then gets stored in a file and is read by an auto prepend file.

I realize that sha512 is definitely overkill but the prefix length is no issue to me as it does not contain any problematic chars.

**Comment by lkraav** [comment]
My first instinct was suggesting to re-use wpdb prefix. It should be a sane value most of the time, no?

**Comment by naxvog** [comment]
The wpdb prefix is troublesome for environments where a single redis database serves more then one WordPress instance

**Comment by tillkruss** [comment]
@naxvog: Thanks, that's useful. The Redis 6 ACL will come in handy then.
