### ISSUE TITLE
Not allowed to access

### ISSUE THREAD

**Issue by SnAFKe** [tillkruss/redis-cache#162]
When i enable redis then i logout and try to login again give me “Not Allowed to Access this Page”.

I try to flush not working, only way to restore to able to login again i need to remove plugin folder.

Any ideas what causing this issue.

**Comment by tillkruss** [comment]
Try a private browser window.

>I try to flush not working

More information please.

**Comment by SnAFKe** [comment]
Already tried, private browser, using another browser,  i repeat same with another computer and phone and still give me that error.

> More information please.

When i flush, i'm able to login then i logout, clean cache/cookies then try again normal and private browser give me back error.

**Comment by tillkruss** [comment]
Try using a different database number, sounds like a conflict.
