### ISSUE TITLE
Excessive comments

### ISSUE THREAD

**Issue by kraftbj** [tillkruss/redis-cache#169]
After a lot of operations, including WP CLI and admin-ajax.php requests (e.g. deleting plugins), seeing this pop up a lot.

```
<!--
Performance optimized by Redis Object Cache. Learn more: https://wprediscache.com

Retrieved 1005 objects (323 KB) from Redis using PhpRedis (v5.2.1).
-->
```

This ends up causing those AJAX requests to fail:
![2020-05-29 at 4 50 PM](https://user-images.githubusercontent.com/88897/83308497-7d8cc800-a1cc-11ea-840d-8cc43a8be864.png)

**Comment by tillkruss** [comment]
Hey @kraftb, I already un-tagged 1.6.0 and working on a fix. Will go live shortly.

**Comment by tillkruss** [comment]
See ac184561e2df7ade391cf2583caf3965c06c88a9

**Comment by tillkruss** [comment]
v1.6.1 is out.

Too many things on my plate today 😓 

![0*zGeb7rTJDBkV9l2O](https://user-images.githubusercontent.com/665029/83309034-0996f380-a1bd-11ea-9baa-5076ee43a53d.jpeg)

**Comment by kraftbj** [comment]
Thanks for the quick response; I've been there!

**Comment by paulkirspuu** [comment]
Still conflicts with some AJAX requests, e.g. FacetWP autocomplete feature.

**Comment by tillkruss** [comment]
@paulkirspuu: Would you mind opening a new issue with some screenshots?

**Comment by naxvog** [comment]
Just for reference: WP-Rocket is doing this using a `is_html` method and obviously output buffering:
```php
/**
 * Tell if the page content is HTML.
 *
 * @since  3.3
 * @access protected
 * @author Grégory Viguier
 *
 * @param  string $buffer The buffer content.
 * @return bool
 */
protected function is_html( $buffer ) {
        return preg_match( '/<\/html>/i', $buffer );
}
```
Why they would use a regular expression is beyond me but we can do it better using `stripos` :wink:

Alternatively we could check the current content type header.
To be quite frank, last time I needed to work with FacetWP it was simply a mess so we can not assume that best practices were used for this AJAX call.

**Comment by lkraav** [comment]
In Pods, I discovered `wp_is_json_request()` exists.

WooCommerce has fun stuff like:

https://github.com/woocommerce/woocommerce/blob/4f344f1357ee87ae22c68d5e0bb6edf489c4a7f8/includes/class-woocommerce.php#L289-L306

**Comment by tillkruss** [comment]
PRs welcome 👍🏻
