### ISSUE TITLE
Composer Installation Path Differs from WordPress Repository Path

### ISSUE THREAD

**Issue by alpipego** [tillkruss/redis-cache#39]
As the title says, when installing the plugin from github via composer (as I did to get the fix for #36) the same include path does not work because it checks for `WP_PLUGIN_DIR . '/redis-cache/includes/predis.php`. With composer (from github) the plugin resides in `/redis-object-cache/`.
I am aware of a workaround (targeting this package explicitly in `installer-paths`), what do you think would be a viable solution to this? Changing the composer package name?

**Comment by tillkruss** [comment]
I'm not sure, I never installed the plugin via Composer. What do you have in mind?

**Comment by alpipego** [comment]
The easiest solution for me would be to change the package name to `redis-cache`. You could mark the package `tillkruss/redis-object-cache` as "abandoned" and superseeded by `tillkruss/redis-cache`. 

I can't tell you however if (or how much) that'll cause problems for users already installing via composer from github. It shouldn't however, cf. https://packagist.org/packages/quandigital/wp-libs

**Comment by alpipego** [comment]
And composer would even warn the user:

<img width="901" alt="screenshot 2016-08-11 17 24 00" src="https://cloud.githubusercontent.com/assets/2003667/17594144/88e1142e-5fe8-11e6-9b56-5c51c5d3c7f0.png">

**Comment by tillkruss** [comment]
Thanks, I'll will do that.
