### ISSUE TITLE
"flush cache" flush all cache on shared redis

### ISSUE THREAD

**Issue by pawawat** [tillkruss/redis-cache#41]
I try setup two wordpress instances and setup unique WP_CACHE_KEY_SALT for each one. When I click "flush cache", plugins flush cache of two instances instead of flushing cache only on that wordpress instance

**Comment by tillkruss** [comment]
Redis's `FLUSHDB` command works per database, so you'd need to use different databases for each installation to prevent that.

The alternative, walking through all keys in the database and checking it's prefix isn't performant. However, if you *really* need that feature, feel free to submit a PR with a feature flag.
