### ISSUE TITLE
Auto activate?

### ISSUE THREAD

**Issue by shaneog** [tillkruss/redis-cache#42]
Is there a way to auto-activate the cache?
I'm adding this to a Docker deployment and I'd like a way to activate the cache automatically.

**Comment by tillkruss** [comment]
This should do it.

```bash
cp /path/to/wp-content/plugins/includes/object-cache.php /path/to/wp-content/object-cache.php
```

You could also submit a PR that add WP CLI command for it specifically. That would be neat.

**Comment by jdegger** [comment]
For anyone looking at this, the correct path is in the redis-cache plugin folder.

Docker command

```
COPY src/wp-content/plugins/redis-cache/includes/object-cache.php ./wp-content/object-cache.php
```
