### ISSUE TITLE
Remove `comments` from the ignored groups for WP 4.6

### ISSUE THREAD

**Issue by stayallive** [tillkruss/redis-cache#45]
Since 4.6 comments can be cached by a persisten storage, would be nice to reflect this here. However I was not sure how this should be handled. I think there are 2 options.

1. Add a note to the docs saying that when you are on 4.6 you should define `WP_REDIS_IGNORED_GROUPS` with `['counts']`
2. Add a WP version compare check to the `WP_Object_Cache` constructor and remove comments if `WP_REDIS_IGNORED_GROUPS` is not set.

Happy to make a PR but wanted to check in first to see which route would be considered best in this plugin.

Reference: https://make.wordpress.org/core/2016/07/18/comments-in-4-6-can-now-be-cached-by-a-persistent-object-cache/

**Comment by tillkruss** [comment]
Thanks!

I've updated the ignore groups in 7f3dfd1005c8ac93362cb14460e96cf959f5cce1 and extended the global groups in bead50c90ca3cdf95a20067274eb59f459e98850.

**Comment by stayallive** [comment]
Thanks for the quick one!
