### ISSUE TITLE
Support redis-sentinel configuration

### ISSUE THREAD

**Issue by andrewmclagan** [tillkruss/redis-cache#55]
Currently this plugin does not support red-sentinel configuration. Although since it does support Predis this is very straight forward.

The issue is in the configuration approach:

````php
    // ...
                if ( defined( 'WP_REDIS_SERVERS' ) ) {
                    $parameters = WP_REDIS_SERVERS;
                    $options[ 'replication' ] = true;
                }
                if ( ( defined( 'WP_REDIS_SERVERS' ) || defined( 'WP_REDIS_CLUSTER' ) ) && defined( 'WP_REDIS_PASSWORD' ) ) {
                    $options[ 'parameters' ][ 'password' ] = WP_REDIS_PASSWORD;
                }
                $this->redis = new Predis\Client( $parameters, $options );
                $this->redis->connect();
````

The `replication` option needs to be set to 'sentinel' not `true`. So would it not be better to have the value of `WP_REDIS_SERVERS` passed directly into the ` $options[ 'replication' ]` variable?

Also a new config param `service` would need to be added... perhaps we could have a new constant called `WP_REDIS_SENTINEL=true` and then `WP_REDIS_CLUSTER` could be set as an array of sentinels.

I would happily  write a PR to do this.

**Comment by andrewmclagan** [comment]
A valid predis config for redis-sentinel looks like:

````php
$sentinels = ['tcp://10.0.0.1', 'tcp://10.0.0.2', 'tcp://10.0.0.3'];
$options   = ['replication' => 'sentinel', 'service' => 'mymaster'];

$client = new Predis\Client($sentinels, $options);
````

**Comment by andrewmclagan** [comment]
I mean... i would even love to have a filter so we can inject our own `Predis\Client` instance.

**Comment by tillkruss** [comment]
Yeah, a filter for the Predis instance would be idea, or maybe even just for the Predis constructor arguments. You might run into issues with that in case `apply_filters()` isn't defined that early. Would love to see a tested PR.
