### ISSUE TITLE
Wrong version/label reported

### ISSUE THREAD

**Issue by cjhaas** [tillkruss/redis-cache#60]
Unless I'm missing something, the version number reported in diagnostics is the version of PhpRedis, not the version of Redis itself.

For instance, PhpRedis is on version 3.1.1 while Redis itself is on version 3.2.8.

For the short-term I think it might be a good idea to re-label that key just to avoid confusing sysadmins (like me). In the long term it might be better to query `$redis->info( 'server' )` and grab the `redis_version` key from that array.

If this is correct I can send a PR for one or the other above although I'm not sure how to show the server version if there are multiple servers defined.

**Comment by tillkruss** [comment]
Yeah, I encountered the same problem and fixed it in https://github.com/tillkruss/redis-cache/commit/664b9624368b6a27850ecb4027998cd9d2665e6b#diff-2436611eee3cca795acb2d69b494fa32, just haven't released a new version yet.
