### ISSUE TITLE
igbinary support

### ISSUE THREAD

**Issue by kevinlisota** [tillkruss/redis-cache#62]
More of a question or feature request, but have you done any work or testing using igbinary as the serializer?

My understanding is that its usage is pretty easy. Just replace the calls to serialize and unserialize with igbinary_serialize and igbinary_unserialize, provided that you compiled PHP with the igbinary extension.

Seems it could save a lot of memory for object cache values, and reduce over-the-wire traffic when communicating with an external redis cache when using multiple web nodes.

**Comment by tillkruss** [comment]
No, never looked into it. My bottleneck is usually the network itself, not size of the data. You're welcome to submit a PR!

**Comment by kevinlisota** [comment]
Testing this out now. I thought this was as simple as replacing the calls to `serialize` and `unserialize` with their igbinary equivalents.

However, digging a little further here, it appears that the the plugin does some string checking to determine whether to serialize or unserialize. igbinary stores in binary form, not strings, so at first glance, this is a bigger change that I first attempted.
