### ISSUE TITLE
Sentinel configuration doesn't work

### ISSUE THREAD

**Issue by ahmed-sigmalux** [tillkruss/redis-cache#63]
I followed the directions in the readme and entered the following in my wp-config.php:

```
define( 'WP_REDIS_CLIENT', 'predis' );
define( 'WP_REDIS_SENTINEL', 'mysentinelname' );
define( 'WP_REDIS_SERVERS', [
  'tcp://10.10.11.11:7010',
  'tcp://10.10.11.12:7010',
] );
define( 'WP_CACHE_KEY_SALT', 'mysalt_' );
define( 'WP_REDIS_SELECTIVE_FLUSH', true );
```

Of course Redis Sentinel instances are running on the above address. I've confirmed I can connect to the addresses via redis-cli.

In Redis Object Cache settings, however, I see this:

```
PHP Version: 7.1.9-1+0~20170902060745.8+stretch~1.gbpebe5d6
Multisite: Yes
Redis: 3.1.2
Predis: 1.1.1
Status: Not Connected
Client: Predis (v1.1.1)
WP_REDIS_CLIENT: "predis"
WP_REDIS_SERVERS: ["tcp:\/\/10.10.11.11:7010","tcp:\/\/10.10.11.12:7010"]
WP_REDIS_MAXTTL: "2678400"
WP_CACHE_KEY_SALT: "mysalt_"
Drop-in: Valid
Global Prefix: ""
Blog Prefix: 1
Global Groups: ["blog-details","blog-id-cache","blog-lookup","global-posts","networks","rss","sites","site-details","site-lookup","site-options","site-transient","users","useremail","userlogins","usermeta","user_meta","userslugs"]
Ignored Groups: ["counts","plugins","blog-details","blog-id-cache","blog-lookup","global-posts","networks","rss","sites","site-details","site-lookup","site-options","site-transient","users","useremail","userlogins","usermeta","user_meta","userslugs","themes"]
```

It seems Redis Object Cache is interpreting the Redis Sentinels as regular Redis servers. Am I doing something wrong?

**Comment by tillkruss** [comment]
The configuration looks correct. I think you'll have to debug that step by step.

**Comment by ahmed-sigmalux** [comment]
Any suggestions on how to debug? As I said, I can connect to the Sentinel instances via redis-cli so I'm not sure where to start.

**Comment by tillkruss** [comment]
I'd just see what the `$parameters` and `$options` are that passed to `new Predis\Client()` and if they are as expected. If so, ask the Predis support team for help with it.
