### ISSUE TITLE
Flush object cache per network site?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [tillkruss/redis-cache#64]
In a multisite setup, can the object cache be flushed per site instead of network-wide?

**Comment by tillkruss** [comment]
No, see https://github.com/tillkruss/redis-cache/pull/33

**Comment by ahmed-sigmalux** [comment]
After reading issue 33, is your position that you don't want to implement per-site cache flushing at all or that you want a pull request for per-site cache flushing that utilizes the existing salt and selective flush options?

**Comment by tillkruss** [comment]
The latter. I'd be delighted to merge a good solution for it.
