### ISSUE TITLE
PHP TypeError when using Sentinel

### ISSUE THREAD

**Issue by synotio** [tillkruss/redis-cache#65]
Hi!

I'm trying to use redis-cache in conjunction with sentinel. I've configured it as mentioned in README.MD except i'm just using one sentinel server for development purposes:

```
define( 'WP_REDIS_CLIENT', 'predis' );
define( 'WP_REDIS_SENTINEL', 'mymaster' );
define( 'WP_REDIS_SERVERS', [
    'tcp://127.0.0.1:26379'
] );
```

When running a WP-CLI command such as `wp redis status` i get the following:

```
Fatal error: Uncaught TypeError: Argument 3 passed to Predis\Connection\Aggregate\SentinelReplication::__construct() must be an instance of Predis\Connection\Aggregate\ConnectionFactoryInterface, instance of Predis\Connection\Factory given, called in /www/wp-content/plugins/redis-cache/includes/predis.php on line 9744 and defined in /www/wp-content/plugins/redis-cache/includes/predis.php:12183
```

According to the commit logs, this plugin uses v1.1.1 of predis. Looking at line 10685 of includes/predis.php [here](https://github.com/tillkruss/redis-cache/blob/master/includes/predis.php#L10685), this version of predis.php however differs from the v1.1.1 release [here](https://github.com/nrk/predis/blob/v1.1.1/src/Connection/Aggregate/SentinelReplication.php#L18)

If I change line 10685 in includes/predis.php to read
`use Predis\Connection\FactoryInterface as ConnectionFactoryInterface;`

instead of 

`use Predis\Connection\FactoryInterface;`

Then the plugin works without problems. PHP Version is 7.1.14 with WordPress 4.8.2

**Comment by tillkruss** [comment]
I just pushed a regenerated Predis file, could you see if `dev-master` works for you?

**Comment by synotio** [comment]
Thanks!

Not really, now I get the following instead:

```
Fatal error: Uncaught Error: Class 'Predis\Configuration\ConnectionFactoryOption' not found in /www/wp-content/plugins/redis-cache/includes/predis.php:9610
```

**Comment by tillkruss** [comment]
I'm out of office for the next two weeks, feel free to fiddle around with it and submit a PR.
