### ISSUE TITLE
Version 1.3.6 breaks wp sites on some servers

### ISSUE THREAD

**Issue by AndreiIgna** [tillkruss/redis-cache#67]
The latest version of the plugin causes a fatal error on some servers, disabling the whole site 
`Fatal error: require(): Failed opening required 'phar://predis.phar/Autoloader.php' (include_path='.:/opt/sp/php7.1/lib/php') in /srv/.../public/wp-content/plugins/redis-cache/includes/predis.php on line 7`

This makes the frontend and wp-admin unusable, the only solution was to reverse the plugin version.

PHP version was switched between 7.0, 7.1 and 7.2, each with same result

Can you help with this?

Cheers

**Comment by tillkruss** [comment]
I'll revert the Predis version this afternoon and release a new version. Thanks for the report.
