### ISSUE TITLE
“Not Allowed to Access this Page” Error in WordPress

### ISSUE THREAD

**Issue by PacoCro** [tillkruss/redis-cache#69]
Today when clicked to enable redis object cache inside plugin dashboard, I received following error:
“Not Allowed to Access this Page”.

I had to delete object-cache.php fom WordPress folder to resolve issue.

Now plugin is not working on my site, though.

Anyone know how to fix this and make plugin work again?

**Comment by tillkruss** [comment]
There are dozens of factors that could cause this. Try flushing the cache and make sure only a single installation is using the same Redis database.
