### ISSUE TITLE
Redis Object Cache NOT compatible with WordPress 4.9.5 - wp-cron not running

### ISSUE THREAD

**Issue by jiripik** [tillkruss/redis-cache#71]
After I upgraded to WP 4.9.5 the wp-cron’s execution was not running any tasks running and I had to disable the addin Redis Object Cache. Once the addin was disabled, the wp-cron again started running well.

Is it a PHP setting problem or Redis Object Cache problem? I am running PHP 7.2.4

**Comment by tillkruss** [comment]
Probably a WP issue. It's a good practise to flush the cache after upgrading WordPress.

**Comment by jiripik** [comment]
Does not help. Even deactivating, reactivating the addin does not help. Even deleting the objectcache.php does not help. As soon as the Redis Object Cache is enabled, the wp-cron.php execution is not processing the cron entries.

Could be php related - the latest wp had some php 7 "improvements".

**Comment by jiripik** [comment]
Would you have time for a quick remote session?

**Comment by jiripik** [comment]
Could the cause be advanced-cache dropin WP-Rocket?

Status: Disabled
Client: 
Drop-in: Invalid
Redis Extension: develop
Predis Client: 1.1.1
PHP Version: 7.2.4
Multisite: No
Dropins: 
 - advanced-cache.php v by

**Comment by tillkruss** [comment]
This plugin is just a cache backend used by WordPress, any application issues are either related to WordPress itself, plugins, themes or custom code. 

I'm not sure what the cache group for the crons is, but you could try disabling that. Checkout the readme for more information.

**Comment by jiripik** [comment]
I understand that and I have no idea why it stopped working after so long working fine. 

If you would like to troubleshoot via a remote desktop, I am available.

**Comment by tillkruss** [comment]
Sure, my hourly rate is $200 USD.

**Comment by jiripik** [comment]
Thanks for the offer. Now, all works so I will take it next time. 

Before WordPress 4.9.5, the plugin did work without PhpRedis. Before WordPress 4.9.5, also the PHP opcache did work. With the 4.9.5 upgrade the opcache was causing segmentation faults so I had to disable it and after I installed the PhpRedis, your plugin started again working!

THANK YOU AGAIN FOR ALL YOUR HELP.
