### ISSUE TITLE
Not connecting to socket file using predis

### ISSUE THREAD

**Issue by chrissound** [tillkruss/redis-cache#75]
I have the following constants:
```
define("WP_REDIS_SCHEME", "unix");
define("WP_REDIS_PATH", "/tmp/docker/redis.sock");
```
I'm able to connect successfully via predis:

```
/var/www/html/wp-content/plugins/redis-cache/includes/predis # php -a
Interactive shell

php > require "autoload.php";
php > $client= new Predis\Client(array('scheme' => 'unix', 'path' => '/tmp/docker/redis.sock'));
php > var_dump($client->ping());
object(Predis\Response\Status)#9 (1) {
  ["payload":"Predis\Response\Status":private]=>
  string(4) "PONG"
}

```

However the admin page has the status set as `Not Connected`:

![2018-06-08-17 40 16](https://user-images.githubusercontent.com/1499652/41172328-0fdd607e-6b43-11e8-999c-c57d06334d1b.png)

If I have a look at `object-cache.php` I don't see predis looking at the two constants above?

**Comment by tillkruss** [comment]
Oh yeah, looks like this was removed and is still in the documentation. I'll remove that. Try connecting via TCP.

**Comment by chrissound** [comment]
Hmm what is the reason for it's removal?

**Comment by tillkruss** [comment]
Not sure. I think it was related to cluster support or something along those lines.
