### ISSUE TITLE
How to solve "Uncaught RedisException: BUSY Redis" error?

### ISSUE THREAD

**Issue by moisb** [tillkruss/redis-cache#77]
Hello, I have little knowledge of Redis, and I tested all the plugins until I chose this as the best. Reading the plugin forums in the WP public repository and the readme here, I got to that config:

**I set these settings in my wp-config:**
`define ('WP_REDIS_DATABASE', '1');
define ('WP_REDIS_SELECTIVE_FLUSH', 'true');
define( 'WP_REDIS_IGNORED_GROUPS', [
    'counts', 
    'plugins', 
    'userlogins', 
    'wordfence', 
    'acf',
    'mailster',
    'themes'
] );`

everything seems to work fine for some time, but after a few days or hours begin to emerge bug logs and strange behaviors in the backend

here are some of the most frequent error logs that appear:
`2018/09/11 14:10:16 [error] 2937#2937: *2372065 redis sent invalid response: "-BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE." while reading response header from upstream, client: 177.91.189.214, server: mywebsite.com, request: "GET /desconto/sao-paulo-mania/ HTTP/1.1", subrequest: "/redis-fetch", upstream: "redis://127.0.0.1:6379", host: "www.mywebsite.com", referrer: "https://www.google.com.br/"
2018/09/11 14:10:16 [error] 2938#2938: *2372062 redis sent invalid response: "-BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE." while reading response header from upstream, client: 177.47.192.42, server: mywebsite.com, request: "GET /desconto/kinguin/cupom-3-off-kinguin-para-todos-os-clientes/ HTTP/1.1", subrequest: "/redis-fetch", upstream: "redis://127.0.0.1:6379", host: "www.mywebsite.com", referrer: "https://www.mywebsite.com/desconto/kinguin/"
2018/09/11 14:10:16 [error] 2938#2938: *2372059 redis sent invalid response: "-BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE." while reading response header from upstream, client: 2804:214:8151:4607:de0a:56f7:597b:9d04, server: mywebsite.com, request: "GET /desconto/shell-box/ HTTP/1.1", subrequest: "/redis-fetch", upstream: "redis://127.0.0.1:6379", host: "www.mywebsite.com", referrer: "http://www.google.com/"
2018/09/11 14:10:16 [error] 2937#2937: *2372041 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RedisException: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE. in /var/www/mywebsite.com/htdocs/wp-content/object-cache.php:722
Stack trace:
#0 /var/www/mywebsite.com/htdocs/wp-content/object-cache.php(722): Redis->get('pegadesconto.co...')
#1 /var/www/mywebsite.com/htdocs/wp-content/object-cache.php(128): WP_Object_Cache->get('easy-social-sha...', 'options', false, NULL)
#2 /var/www/mywebsite.com/htdocs/wp-includes/option.php(95): wp_cache_get('easy-social-sha...', 'options')
#3 /var/www/mywebsite.com/htdocs/wp-content/plugins/easy-social-share-buttons3/lib/essb-core-includes.php(159): get_option('easy-social-sha...')
#4 /var/www/mywebsite.com/htdocs/wp-content/plugins/easy-social-share-buttons3/easy-social-share-buttons3.php(260): include_once('/var/www/pegade...')
#5 /var/www/mywebsite.com/htdocs/wp-includes/class-wp-hook.php(286): ESSB_Manager->load_widgets('')
#6 /var/www/pegadesc...
PHP message: PHP Fatal error:  Uncaught RedisException: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE. in /var/www/mywebsite.com/htdocs/wp-content/object-cache.php:722
Stack trace:
#0 /var/www/mywebsite.com/htdocs/wp-content/object-cache.php(722): Redis->get('pegadesconto.co...')
#1 /var/www/mywebsite.com/htdocs/wp-content/object-cache.php(128): WP_Object_Cache->get('bnfw-cf-notific...', 'transient', false, NULL)
#2 /var/www/mywebsite.com/htdocs/wp-includes/option.php(673): wp_cache_get('bnfw-cf-notific...', 'transient')
#3 /var/www/mywebsite.com/htdocs/wp-content/plugins/bnfw-custom-fields/includes/class-bnfw-custom-field-notification.php(270): get_transient('bnfw-cf-notific...')
#4 /var/www/mywebsite.com/htdocs/wp-includes/class-wp-hook.php(286): BNFW_Custom_Field_Notification->on_shutdown('')
#5 /var/www/mywebsite.com/htdocs/wp-includes/class-wp-hook.ph
2018/09/11 14:10:16 [error] 2937#2937: *2372010 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RedisException: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE. in /var/www/mywebsite.com/htdocs/wp-content/object-cache.php:838
Stack trace:
#0 /var/www/mywebsite.com/htdocs/wp-content/object-cache.php(838): Redis->set('pegadesconto.co...', 9403)
#1 /var/www/mywebsite.com/htdocs/wp-content/object-cache.php(227): WP_Object_Cache->set('rocket_sitemap_...', 9403, 'transient', 0)
#2 /var/www/mywebsite.com/htdocs/wp-includes/option.php(756): wp_cache_set('rocket_sitemap_...', 9403, 'transient', 0)
#3 /var/www/mywebsite.com/htdocs/wp-content/plugins/wp-rocket/inc/classes/background-processing.php(71): set_transient('rocket_sitemap_...', 9403)
#4 /var/www/mywebsite.com/htdocs/wp-content/plugins/woocommerce/includes/libraries/wp-background-process.php(301): Rocket_Sitemap_Preload_Process->task('https://www.peg...')
#5 /var/www/mywebsite.com/htdocs/wp-content/plugins/woocommerce/includes/librar...
PHP message: PHP Fatal error:  Uncaught RedisException: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE. in /var/www/mywebsite.com/htdocs/wp-content/object-cache.php:722`

I find some kind of incompatibility with other plugins like "WP Rocket Cache" (I use for minify, combine and cache to disk), "Better Notifications for WordPress", "Easy Social Share Buttons", "Woocommerce" etc.
But I do not know exactly what to do and I'm almost giving up using Redis Cache :( 
Can someone help me?

**Comment by tillkruss** [comment]
Try disabling `WP_REDIS_SELECTIVE_FLUSH`.
