### ISSUE TITLE
WP_REDIS_PASSWORD permanent status : Not connected

### ISSUE THREAD

**Issue by VGzsysadm** [tillkruss/redis-cache#82]
Greetings.

I saw the following command WP_REDIS_PASSWORD  it's seems not working with the last WPv4.9.8

The diagnostic error is this:

Status: Not Connected
Client: PhpRedis (v4.1.1)
Drop-in: Valid
Ping: PONG
Redis Extension: 4.1.1
Predis Client: 1.1.1
PHP Version: 7.2.11-2+0~20181015120801.9+stretch~1.gbp8105e0
Multisite: No
Global Prefix: "wp_"
Blog Prefix: "wp_"
WP_REDIS_CLIENT: "predis"
WP_REDIS_SCHEME: "tcp"
WP_REDIS_HOST: "127.0.0.1"
WP_REDIS_PORT: "6379"
WP_REDIS_PASSWORD: "**************"
Global Groups: ["blog-details","blog-id-cache","blog-lookup","global-posts","networks","rss","sites","site-details","site-lookup","site-options","site-transient","users","useremail","userlogins","usermeta","user_meta","userslugs"]
Ignored Groups: ["counts","plugins","blog-details","blog-id-cache","blog-lookup","global-posts","networks","rss","sites","site-details","site-lookup","site-options","site-transient","users","useremail","userlogins","usermeta","user_meta","userslugs","themes"]
Dropins: 
 - Redis Object Cache Drop-In v1.3.8 by Till Krüss
Plugins: 
 - Redis Object Cache v1.3.8 by Till Krüss (Active)

wp-config -> 

//** Redis Config. */
define('WP_CACHE', true);
define('WP_REDIS_CLIENT', 'predis');
define('WP_REDIS_SCHEME', 'tcp');
define('WP_REDIS_HOST', '127.0.0.1');
define('WP_REDIS_PORT', '6379');
define('WP_REDIS_PASSWORD', 'foobar');

redis-cli -a foobar -> works without any kind of problem.

If i comment the entry "#requirepass foobar" at redis.conf the connection works successful and i can see the content caching at the monitor.

Anyone can confirm this?

Thanks for your time.

Kind regards.

**Comment by tillkruss** [comment]
>Ping: PONG

Means that the drop-in connected successfully to your Redis instance.

I'm not sure why it says `Not Connected`, you'll have to debug that.

**Comment by tillkruss** [comment]
@VGzsysadm: Did you figure it out?
