### ISSUE TITLE
Support: Multisite flush cache

### ISSUE THREAD

**Issue by killua99** [tillkruss/redis-cache#83]
Hi,

I was you allow to clear certains key when the definition to do it is defined. but, I'm looking something to clear the entire redis cache from a single site, and not the entire redis db cache.

I'm confuse if wp_cache_flush() will react only per site, and not the entire redis data, seems to clear the entire db tho.

There is a way to do this? to clear a single site in a multisite setup?
If not, will you allow a pr to add this feature ?

**Comment by tillkruss** [comment]
I'd suggest you look into how the object cache of WordPress works. You might also want to look at `WP_REDIS_SELECTIVE_FLUSH`.

**Comment by killua99** [comment]
is not that simple to use the `WP_REDIS_SELECTIVE_FLUSH` with `WP_CACHE_KEY_SALT`per multisite, there's no option or way to work nicely with it.

I wasn't confuse, it was clear, the flush will delete the database. I was concern about the UI button that flush it. I want to add a button to clear just the site cache and not the entire redis database.

**Comment by tillkruss** [comment]
Feel free to submit a PR.
