### ISSUE TITLE
support for wp_suspend_cache_*

### ISSUE THREAD

**Issue by pySilver** [tillkruss/redis-cache#84]
Hi!

Shouldn't we support `wp_suspend_cache_invalidation` & `wp_suspend_cache_addition`. Otherwise it bloats local memory when doing huge imports.

**Comment by tillkruss** [comment]
Can you submit a PR?

**Comment by tillkruss** [comment]
`wp_suspend_cache_invalidation()` seems to be handled by WordPress and 3rd party code.

I added a `wp_suspend_cache_addition()` check in 5b0fde4.

**Comment by pySilver** [comment]
@tillkruss sorry for silence, my current env is not the best for PR so I had to hardcode this changes. I ended up to add this `wp_suspend_cache_invalidation` in a little bit different places than you:

\wp_cache_set
