### ISSUE TITLE
2 warnings PHP

### ISSUE THREAD

**Issue by Camilo517** [tillkruss/redis-cache#86]
Hello :)
redis-cache/includes/predis/src/Collection/Iterator/HashKey.php
53 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead

redis-cache/includes/predis/src/Collection/Iterator/SortedSetKey.php
53 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead

**Comment by tillkruss** [comment]
Hey! Would you mind reporting that here: https://github.com/nrk/predis ?

**Comment by Camilo517** [comment]
I already commented, thanks

Do you recommend any special configuration in woocommerce?

**Comment by tillkruss** [comment]
Not really, WC seems to be using the WP cache well. If you run into issues, you can always disable the WC cache groups to avoid issues.
