### ISSUE TITLE
Use AWS Cluster with read-only replicas

### ISSUE THREAD

**Issue by bherrero** [tillkruss/redis-cache#88]
Hello,

we have a default AWS elasticache Redis cluster, and we would like to know if there's any chance of setting the plugin up to use one primary node (writable) and one or more replicas which are read-only.

Can this be done with this plugin? If so, how should we configure it?

Thanks so much.

**Comment by tillkruss** [comment]
I don't think that's even possible technically. Isn't ElastiCache a "true" cluster anyhow?

I'd suggest the regular cluster configuration:
```php
define( 'WP_REDIS_CLUSTER', [
    'tcp://127.0.0.1:6379?database=0&alias=node-01',
    'tcp://127.0.0.2:6379?database=0&alias=node-02',
] );
```

Feel free to experiment with the master-replica configuration tho:

```php
define( 'WP_REDIS_SERVERS', [
    'tcp://127.0.0.1:6379?database=0&alias=master',
    'tcp://127.0.0.2:6379?database=0&alias=slave-01',
    'tcp://127.0.0.3:6379?database=0&alias=slave-02,
] );
```

**Comment by bherrero** [comment]
Thanks for your answer. Well, it is possible. We've been working with that for a while with other projects. We'll try the options you're suggesting, thank you.

**Comment by tillkruss** [comment]
When you get it to work, post your setup for others here please :-)

**Comment by ethanclevenger91** [comment]
@bherrero Did you ever get this working properly?

As far as whether or not it's possible, Elasticache provides two endpoints. Seems like I'm expected to use them: 
![image](https://user-images.githubusercontent.com/2623646/67711646-a1123a80-f97f-11e9-94d4-78790a9cf6a4.png)

Right now there are two nodes, one "primary" and one "replica", and the replica one doesn't seem to be used.

**Comment by tillkruss** [comment]
Yeah, currently read-only endpoints can’t be used. The upcoming business version will support it however.
