### ISSUE TITLE
call to undefined wp_suspend_cache_addition

### ISSUE THREAD

**Issue by kevinlisota** [tillkruss/redis-cache#89]
Latest update (1.4.) threw this error on our site continuously when I installed it

PHP Fatal error:  Uncaught Error: Call to undefined function wp_suspend_cache_addition() in /var/www/mysite.com/wp-content/object-cache.php:584

Obviously `wp_suspend_cache_addition` is part of WP core. I'm guessing that object-cache.php is being loaded before that function exists, but haven't dug around to see what the exact loading order is in WP.

Will research more, but does this need a `function_exists`?

**Comment by tillkruss** [comment]
Strange. Thanks for the report. I'll release an update shortly.

**Comment by tillkruss** [comment]
@kevinlisota: Would you mind testing this version to see whether that fixes the issue? 
https://github.com/tillkruss/redis-cache/archive/master.zip

**Comment by tillkruss** [comment]
No need to worry about it. I'll release the update shortly.
