### ISSUE TITLE
`redis_object_cache_get` called twice with reversed parameters

### ISSUE THREAD

**Issue by soulseekah** [tillkruss/redis-cache#90]
The `redis_object_cache_get` action is also a filter but with switched parameters.

![image](https://user-images.githubusercontent.com/685880/50168763-39ba4180-02fd-11e9-8224-a5188423abf5.png)

The first parameter is they key when in an action and the value when in a filter. Actions are filters, filters are actions.

So when adding an action or filter it's called twice: once with the expected parameter order, the other with the first two parameters switched.

This is obviously a huge issue.

How would you like to approach this?

1. Rename the filter and/or the action.
2. Switch the parameters to be `( $value, $key, .. )` for the action.
3. something else?

**Comment by soulseekah** [comment]
I don't think 2 will work, as the action is now expected to return something as its callback is shared. This goes against the concept altogether.

So doing `add_action( 'redis_object_cache_get', function() ...` effectively breaks cache because the `appy_filters` call below will call the action a second time and get a `null` value. All caches are now `null`.

The only way to differentiate between the two is to check the backtrace and look whether the 2nd or 3rd calling functions are `do_action` or `apply_filters`, no other way as far as I've wrecked my head.

**Comment by soulseekah** [comment]
We opted in for a counter instead. For performance reasons:

![image](https://user-images.githubusercontent.com/685880/50169914-afbfa800-02ff-11e9-95dd-af4b9fa0fa26.png)

**Comment by tillkruss** [comment]
It makes no sense that they have the same name. That was a sloppy merge of me in #29.

There are several actions, so I'd say let's rename the one filter as well as swap the parameter order.

How about this?

```php
apply_filters( 'redis_object_cache_get_value', $key, $value, $group, $force, $found );
```

**Comment by soulseekah** [comment]
The `apply_filters` should filter the value, not the key, so the parameter order for it is good.

It just needs the rename. I'll submit a PR shortly.
