### ISSUE TITLE
Extend $fail_gracefully to other methods rather than only constructor

### ISSUE THREAD

**Issue by desaiuditd** [tillkruss/redis-cache#97]
**Context:**

The `WP_Object_Cache` class takes `$fail_gracefully` variable as parameter in its constructor. And the Redis Object Cache fails gracefully without throwing any exception if it fails to connect to Redis.

But this does not extend to other methods i.e., `add`, `replace`, `add_or_replace`, `delete`, `get`, `set` etc.

This is fine when the Redis connectivity is checked in the constructor. But let's say if Redis connectivity is lost for some unknown reasons (network failures, Redis server failures etc.) at later stage after constructor is already executed, the plugin will throw an exception and the php process will terminate abruptly.

**Proposal:**
Store the `$fail_gracefully` variable as private class variable. And respect its value in other methods as well along with the constructor such as `add`, `replace`, `set`, `get` etc.

With this, all the methods of `WP_Object_Cache` class will fail gracefully in case of an error.

Open for other suggestions. This scenario was exposed in the production environment of one of the project that I'm working on.

**Comment by tillkruss** [comment]
This is great! I'm going to merge it next week 👌🏻
