### ISSUE TITLE
Call to undefined method redis_status() when WP_REDIS_DISABLED

### ISSUE THREAD

**Issue by ethanclevenger91** [tillkruss/redis-cache#99]
The admin page for managing Redis throws a fatal PHP error if you've set `WP_REDIS_DISABLED` to true. Would be nice if this were a bit more graceful, probably notifying you that Redis has been otherwise disabled.

```
PHP Fatal error: Uncaught Error: Call to undefined method WP_Object_Cache::redis_status() when WP_REDIS_DISABLED true
```

**Comment by tillkruss** [comment]
Checkout #97.

**Comment by tillkruss** [comment]
@ethanclevenger91: Can you post the error message?

**Comment by ethanclevenger91** [comment]
It's the one in the title. Call to undefined method
WP_Object_Cache::redis_status(). I'll look at that other issue

**Comment by tillkruss** [comment]
Ah, thanks! I was rushing out of the door.

**Comment by tillkruss** [comment]
@ethanclevenger91: Can you please post the entire stack trace, so I know where it's being called from?

**Comment by ethanclevenger91** [comment]
I don't even get a full stack trace, oddly enough. No Debug Bar plugin.

So with your plugin, and its drop-in, active, I add `define('WP_REDIS_DISABLED', true);` to the wp-config.php file. Then navigate to Settings -> Redis and get the following:

![image](https://user-images.githubusercontent.com/2623646/57151198-24622300-6d85-11e9-9e97-43d37baded12.png)

If I cause other notices to be thrown before this (for example, defining a constant twice), I do get the XDEBUG output, so not sure why this is showing up like this.

**Comment by ethanclevenger91** [comment]
Disabled all non-Redis plugins and made it to the settings page, though not without the same fatal error. But now I get the XDEBUG trace.

```
( ! ) Error: Call to undefined method WP_Object_Cache::redis_status() in /home/vagrant/dev/collider/wp-content/plugins/redis-cache/redis-cache.php on line 171
--


1 | 0.0022 | 417856 | {main}( ) | .../options-general.php:0
2 | 0.0028 | 418528 | require_once( '/home/vagrant/dev/collider/wp-admin/admin.php' ) | .../options-general.php:10
3 | 0.2176 | 4246112 | do_action( ) | .../admin.php:224
4 | 0.2176 | 4246488 | WP_Hook->do_action( ) | .../plugin.php:453
5 | 0.2176 | 4246488 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:310
6 | 0.2176 | 4247616 | RedisObjectCache->show_admin_page( ) | .../class-wp-hook.php:286
7 | 0.2181 | 4248096 | require_once( '/home/vagrant/dev/collider/wp-content/plugins/redis-cache/includes/admin-page.php') | .../redis-cache.php:92
8 | 0.2183 | 4248096 | RedisObjectCache->get_status( ) | .../admin-page.php:38
9 | 0.2204 | 4248096 | RedisObjectCache->get_redis_status( ) | .../redis-cache.php:153
```

**Comment by tillkruss** [comment]
Fixed in https://github.com/tillkruss/redis-cache/commit/807acff8bf8a44045bbbedd88507fd053f889eab.

**Comment by tillkruss** [comment]
@ethanclevenger91: Can you download `master` and see if that resolves it for you as well?

**Comment by ethanclevenger91** [comment]
Hey @tillkruss the new version did fix the issue - much more graceful. Thanks!
